// <auto-generated />
using System;
using Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(InternshipAppDbContext))]
    partial class InternshipAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Data.Entities.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BannedUntil")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReputationPoints")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BannedUntil = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ivo",
                            Password = "",
                            ReputationPoints = 1000000,
                            Surname = "Sanader",
                            Username = "HDZ"
                        },
                        new
                        {
                            Id = 2,
                            BannedUntil = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Marjan",
                            Password = "",
                            ReputationPoints = 10000,
                            Surname = "Marjanovic",
                            Username = "asdasd"
                        },
                        new
                        {
                            Id = 3,
                            BannedUntil = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ivo",
                            Password = "",
                            ReputationPoints = 1,
                            Surname = "Ivic",
                            Username = "asfffassf"
                        },
                        new
                        {
                            Id = 4,
                            BannedUntil = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pero",
                            Password = "",
                            ReputationPoints = 1,
                            Surname = "Peric",
                            Username = "sd"
                        });
                });

            modelBuilder.Entity("Data.Entities.Models.Perceive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PerceiverId")
                        .HasColumnType("int");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PerceiverId");

                    b.HasIndex("ResourceId");

                    b.ToTable("Perceptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PerceiverId = 1,
                            ResourceId = 1
                        },
                        new
                        {
                            Id = 2,
                            PerceiverId = 1,
                            ResourceId = 2
                        },
                        new
                        {
                            Id = 3,
                            PerceiverId = 1,
                            ResourceId = 3
                        });
                });

            modelBuilder.Entity("Data.Entities.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Posts");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Post");
                });

            modelBuilder.Entity("Data.Entities.Models.Reaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CommentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsUpVote")
                        .HasColumnType("bit");

                    b.Property<int>("ReactorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("ReactorId");

                    b.ToTable("Reactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommentId = 4,
                            IsUpVote = true,
                            ReactorId = 1
                        },
                        new
                        {
                            Id = 2,
                            CommentId = 5,
                            IsUpVote = true,
                            ReactorId = 1
                        },
                        new
                        {
                            Id = 3,
                            CommentId = 6,
                            IsUpVote = true,
                            ReactorId = 1
                        },
                        new
                        {
                            Id = 4,
                            CommentId = 7,
                            IsUpVote = true,
                            ReactorId = 1
                        });
                });

            modelBuilder.Entity("Data.Entities.Models.Comment", b =>
                {
                    b.HasBaseType("Data.Entities.Models.Post");

                    b.Property<int?>("CommentId")
                        .HasColumnType("int");

                    b.Property<int>("DownVotes")
                        .HasColumnType("int");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.Property<int>("UpVotes")
                        .HasColumnType("int");

                    b.HasIndex("CommentId");

                    b.HasIndex("ResourceId");

                    b.HasDiscriminator().HasValue("Comment");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            AuthorId = 1,
                            Date = new DateTime(2020, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Hehehehehehehehehehe",
                            DownVotes = 1,
                            ResourceId = 1,
                            UpVotes = 3
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 2,
                            Date = new DateTime(2020, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Hehehehehehehehehehe",
                            CommentId = 4,
                            DownVotes = 1,
                            ResourceId = 1,
                            UpVotes = 3
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 3,
                            Date = new DateTime(2020, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Hehehehehehehehehehe",
                            CommentId = 5,
                            DownVotes = 1,
                            ResourceId = 1,
                            UpVotes = 3
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 1,
                            Date = new DateTime(2020, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "hohohohohoho",
                            DownVotes = 1,
                            ResourceId = 2,
                            UpVotes = 3
                        });
                });

            modelBuilder.Entity("Data.Entities.Models.Resource", b =>
                {
                    b.HasBaseType("Data.Entities.Models.Post");

                    b.Property<int>("Domain")
                        .HasColumnType("int");

                    b.Property<string>("Header")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeenCounter")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Resource");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Date = new DateTime(2020, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Hehehehehehehehehehe",
                            Domain = 4,
                            Header = "Hehe",
                            SeenCounter = 4
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            Date = new DateTime(2020, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "hohohohhohohohohohohoho",
                            Domain = 4,
                            Header = "Hoho",
                            SeenCounter = 4
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            Date = new DateTime(2020, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Text = "Lorem ipsum or sumtin",
                            Domain = 3,
                            Header = "Nešto smisleno",
                            SeenCounter = 4
                        });
                });

            modelBuilder.Entity("Data.Entities.Models.Perceive", b =>
                {
                    b.HasOne("Data.Entities.Models.Member", "Perceiver")
                        .WithMany("Perceptions")
                        .HasForeignKey("PerceiverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Data.Entities.Models.Resource", "Resource")
                        .WithMany("Perceptions")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Perceiver");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Data.Entities.Models.Post", b =>
                {
                    b.HasOne("Data.Entities.Models.Member", "Author")
                        .WithMany("Posts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Data.Entities.Models.Reaction", b =>
                {
                    b.HasOne("Data.Entities.Models.Comment", "Comment")
                        .WithMany("Reactions")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Data.Entities.Models.Member", "Reactor")
                        .WithMany("Reactions")
                        .HasForeignKey("ReactorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("Reactor");
                });

            modelBuilder.Entity("Data.Entities.Models.Comment", b =>
                {
                    b.HasOne("Data.Entities.Models.Comment", "ParentComment")
                        .WithMany("Comments")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Data.Entities.Models.Resource", "Resource")
                        .WithMany("Comments")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ParentComment");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Data.Entities.Models.Member", b =>
                {
                    b.Navigation("Perceptions");

                    b.Navigation("Posts");

                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("Data.Entities.Models.Comment", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("Data.Entities.Models.Resource", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Perceptions");
                });
#pragma warning restore 612, 618
        }
    }
}
